// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORUV4567vfuRnE-4C6tyehFAlG9Ficew',
    appId: '1:1067299307317:web:ae4401f146bc752c8fd67c',
    messagingSenderId: '1067299307317',
    projectId: 'coworking-db',
    authDomain: 'coworking-db.firebaseapp.com',
    storageBucket: 'coworking-db.appspot.com',
    measurementId: 'G-GBSY4LM910',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnT-T5ZwCbwNEMMekCSXqSl7F3crCErKw',
    appId: '1:1067299307317:android:d40a8d11761434118fd67c',
    messagingSenderId: '1067299307317',
    projectId: 'coworking-db',
    storageBucket: 'coworking-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkO3xiGTgADVRI2A74H8P9dejhW2c7ZbI',
    appId: '1:1067299307317:ios:62ea7b4b8973a4768fd67c',
    messagingSenderId: '1067299307317',
    projectId: 'coworking-db',
    storageBucket: 'coworking-db.appspot.com',
    iosBundleId: 'com.example.coworkingSpaceMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkO3xiGTgADVRI2A74H8P9dejhW2c7ZbI',
    appId: '1:1067299307317:ios:62ea7b4b8973a4768fd67c',
    messagingSenderId: '1067299307317',
    projectId: 'coworking-db',
    storageBucket: 'coworking-db.appspot.com',
    iosBundleId: 'com.example.coworkingSpaceMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBORUV4567vfuRnE-4C6tyehFAlG9Ficew',
    appId: '1:1067299307317:web:53ee676350d8250d8fd67c',
    messagingSenderId: '1067299307317',
    projectId: 'coworking-db',
    authDomain: 'coworking-db.firebaseapp.com',
    storageBucket: 'coworking-db.appspot.com',
    measurementId: 'G-VXHGMWR2BP',
  );
}
